title: dotIgnore
description: A unified format for ignore files across all version control systems
baseurl: ""
url: "https://dotignore.com"
github_username: sav-vcs
repository: sav-vcs/dotignore

# Build settings
markdown: kramdown
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-github-metadata

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git/
  - LICENSE
  - CONTRIBUTING.md
  - docker-compose.yml
  - Dockerfile
  - .dockerignore
  - .gitignore
  - Cargo.toml
  - Cargo.lock
  - src/
  - tests/
  - samples/

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:path/ 